# Generated by Django 5.2.12 on 2026-09-18 00:54

import django.db.models.deletion
import netbox.models.deletion
import netbox_tco.models
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('extras', '0134_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('object_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=netbox_tco.models.attachment_upload_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'netbox_tco'), ('model__in', ['qpi', 'supportcontract', 'license'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('status', models.CharField(default='active', max_length=50)),
                ('renewal_status', models.CharField(default='ok', editable=False, max_length=50)),
                ('predecessors', models.ManyToManyField(blank=True, related_name='successors', to='netbox_tco.license')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='netbox_tco_licenses', to='dcim.manufacturer')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LicensePartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='netbox_tco_license_part_numbers', to='dcim.manufacturer')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_numbers', to='netbox_tco.licensetype')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='LicenseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('billing_term', models.CharField(default='subscription', max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('license_key', models.CharField(blank=True, max_length=500)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netbox_tco_license_lines', to='dcim.device')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_lines', to='netbox_tco.license')),
                ('license_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='license_lines', to='netbox_tco.licensetype')),
            ],
            options={
                'ordering': ['license', 'device'],
            },
        ),
        migrations.CreateModel(
            name='LifecycleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('reference_url', models.URLField(blank=True)),
                ('notice_date', models.DateField(blank=True, null=True)),
                ('device_types', models.ManyToManyField(blank=True, related_name='netbox_tco_lifecycle_records', to='dcim.devicetype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LifecycleMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('milestone_type', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('lifecycle_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='netbox_tco.lifecyclerecord')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('line_type', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_months', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='netbox_tco_line_items', to='dcim.devicetype')),
                ('license_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='netbox_tco.licensepartnumber')),
                ('provisioned_devices', models.ManyToManyField(blank=True, related_name='netbox_tco_source_line_items', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['qpi', 'line_type'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='license',
            name='funding_line_items',
            field=models.ManyToManyField(blank=True, limit_choices_to={'line_type': 'license'}, related_name='netbox_tco_funded_licenses', to='netbox_tco.lineitem'),
        ),
        migrations.CreateModel(
            name='QPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(default='requested', max_length=50)),
                ('quote_requested', models.DateField(blank=True, null=True)),
                ('quote_received', models.DateField(blank=True, null=True)),
                ('quote_signed', models.DateField(blank=True, null=True)),
                ('quote_returned', models.DateField(blank=True, null=True)),
                ('auto_populate_returned', models.BooleanField(default=True)),
                ('shipping_receiving', models.DateField(blank=True, null=True)),
                ('owners', models.ManyToManyField(blank=True, related_name='netbox_tco_owned_qpis', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'QPI',
                'ordering': ['-created'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='qpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='netbox_tco.qpi'),
        ),
        migrations.CreateModel(
            name='ServiceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceLevelPartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='netbox_tco_service_level_part_numbers', to='dcim.manufacturer')),
                ('service_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_numbers', to='netbox_tco.servicelevel')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.AddField(
            model_name='lineitem',
            name='support_sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='netbox_tco.servicelevelpartnumber'),
        ),
        migrations.CreateModel(
            name='SupportContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('contract_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='active', max_length=50)),
                ('renewal_status', models.CharField(default='ok', editable=False, max_length=50)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('funding_line_items', models.ManyToManyField(blank=True, limit_choices_to={'line_type': 'support'}, related_name='netbox_tco_funded_support_contracts', to='netbox_tco.lineitem')),
                ('predecessors', models.ManyToManyField(blank=True, related_name='successors', to='netbox_tco.supportcontract')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='netbox_tco_support_contracts', to='dcim.manufacturer')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CoverageLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='netbox_tco_coverage_lines', to='dcim.device')),
                ('service_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage_lines', to='netbox_tco.servicelevel')),
                ('support_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_lines', to='netbox_tco.supportcontract')),
            ],
            options={
                'ordering': ['support_contract', 'device'],
            },
        ),
    ]
