# Generated by Django 5.2.12 on 2026-10-02 03:59

import django.db.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0134_owner'),
        ('netbox_tco', '0005_lineitem_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coverageline',
            options={'ordering': ['support_contract', '-end_date', 'pk']},
        ),
        migrations.AlterModelOptions(
            name='supportcontract',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='coverageline',
            name='device',
        ),
        migrations.RemoveField(
            model_name='supportcontract',
            name='funding_line_items',
        ),
        migrations.AddField(
            model_name='coverageline',
            name='assigned_object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coverageline',
            name='assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'dcim'), ('model__in', ['device', 'module'])), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='coverageline',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='coverageline',
            name='custom_field_data',
            field=models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
        ),
        migrations.AddField(
            model_name='coverageline',
            name='funding_line_item',
            field=models.ForeignKey(blank=True, limit_choices_to={'line_type': 'support'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_lines', to='netbox_tco.lineitem'),
        ),
        migrations.AddField(
            model_name='coverageline',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='coverageline',
            name='status',
            field=models.CharField(default='pending', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='coverageline',
            name='tags',
            field=taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag'),
        ),
        migrations.AddField(
            model_name='supportcontract',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportcontract',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='coverageline',
            index=models.Index(fields=['assigned_object_type', 'assigned_object_id'], name='netbox_tco__assigne_397673_idx'),
        ),
    ]
