# Generated by Django 5.2.12 on 2026-10-02 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('netbox_tco', '0007_pillar5_licenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecyclerecord',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lifecyclerecord',
            name='module_types',
            field=models.ManyToManyField(blank=True, related_name='netbox_tco_lifecycle_records', to='dcim.moduletype'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'netbox_tco'), ('model__in', ['qpi', 'supportcontract', 'license', 'lifecyclerecord'])), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddConstraint(
            model_name='lifecyclemilestone',
            constraint=models.UniqueConstraint(fields=('lifecycle_record', 'milestone_type'), name='netbox_tco_milestone_unique_type_per_record'),
        ),
    ]
