# Generated by Django 5.2.12 on 2026-10-02 17:13

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.fields
import utilities.json
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


# The four types the plugin used to ship as the 'milestone_types' setting, with a color and order
DEFAULT_TYPES = [
    ('End of Sale', 'ff9800'),
    ('End of SW Maintenance', 'ffc107'),
    ('End of Security Support', 'f44336'),
    ('End of Support', '9c27b0'),
]


def seed_and_link(apps, schema_editor):
    """
    Create MilestoneType rows from the old 'milestone_types' setting (an admin's custom list, else the
    defaults), plus any other value already used on a milestone, then point each milestone at its row.
    """
    MilestoneType = apps.get_model('netbox_tco', 'MilestoneType')
    LifecycleMilestone = apps.get_model('netbox_tco', 'LifecycleMilestone')
    colors = dict(DEFAULT_TYPES)
    configured = settings.PLUGINS_CONFIG.get('netbox_tco', {}).get('milestone_types') or [n for n, _ in DEFAULT_TYPES]
    used = LifecycleMilestone.objects.order_by().values_list('milestone_type_name', flat=True).distinct()
    names = list(dict.fromkeys(list(configured) + sorted(used)))
    by_name = {}
    for i, name in enumerate(names):
        slug, n = slugify(name)[:90] or 'milestone', 2
        base = slug
        while MilestoneType.objects.filter(slug=slug).exists():
            slug, n = f'{base}-{n}', n + 1
        by_name[name] = MilestoneType.objects.create(
            name=name, slug=slug, color=colors.get(name, '9e9e9e'), weight=(i + 1) * 10,
        )
    for m in LifecycleMilestone.objects.all():
        m.milestone_type = by_name[m.milestone_type_name]
        m.save(update_fields=['milestone_type'])


def unlink(apps, schema_editor):
    LifecycleMilestone = apps.get_model('netbox_tco', 'LifecycleMilestone')
    for m in LifecycleMilestone.objects.select_related('milestone_type'):
        m.milestone_type_name = m.milestone_type.name
        m.save(update_fields=['milestone_type_name'])


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_tco', '0008_pillar6_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('color', utilities.fields.ColorField(default='9e9e9e', max_length=6)),
                ('weight', models.PositiveSmallIntegerField(default=100)),
                ('description', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'ordering': ['weight', 'name'],
                'verbose_name': 'EOx milestone',
                'verbose_name_plural': 'EOx milestones',
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='lifecyclemilestone',
            name='netbox_tco_milestone_unique_type_per_record',
        ),
        migrations.RenameField(
            model_name='lifecyclemilestone',
            old_name='milestone_type',
            new_name='milestone_type_name',
        ),
        migrations.AddField(
            model_name='lifecyclemilestone',
            name='milestone_type',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name='milestones',
                to='netbox_tco.milestonetype',
            ),
        ),
        migrations.RunPython(seed_and_link, unlink),
        # A default lets a rollback re-add the old column to a table that already has rows
        migrations.AlterField(
            model_name='lifecyclemilestone',
            name='milestone_type_name',
            field=models.CharField(max_length=200, default=''),
        ),
        migrations.RemoveField(
            model_name='lifecyclemilestone',
            name='milestone_type_name',
        ),
        migrations.AlterField(
            model_name='lifecyclemilestone',
            name='milestone_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name='milestones',
                to='netbox_tco.milestonetype',
            ),
        ),
        migrations.AddConstraint(
            model_name='lifecyclemilestone',
            constraint=models.UniqueConstraint(
                fields=('lifecycle_record', 'milestone_type'), name='netbox_tco_milestone_unique_type_per_record',
            ),
        ),
        migrations.AlterModelOptions(
            name='lifecyclemilestone',
            options={'ordering': ['date', 'milestone_type__weight']},
        ),
    ]
