# Generated by Django 5.2.12 on 2026-10-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dcim', '0226_modulebay_rebuild_tree'),
        ('netbox_tco', '0009_milestone_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifecyclerecord',
            name='rack_types',
            field=models.ManyToManyField(blank=True, related_name='netbox_tco_lifecycle_records', to='dcim.racktype'),
        ),
        migrations.AlterField(
            model_name='coverageline',
            name='assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'dcim'), ('model__in', ['device', 'module', 'rack'])), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='licenseline',
            name='assigned_object_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'dcim'), ('model__in', ['device', 'module', 'rack'])), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype'),
        ),
    ]
